<?php

use App\Models\Continente;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $continente_asia = Continente::where('nome', 'Ásia')->first();
        $continente_america = Continente::where('nome', 'América')->first();
        $continente_africa = Continente::where('nome', 'África')->first();
        $continente_europa = Continente::where('nome', 'Europa')->first();
        $continente_oceanea = Continente::where('nome', 'Oceania')->first();

        DB::table('pais')->insert([
            ['nome' => 'Afeganistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Arábia Saudita', 'continente_id' => $continente_asia->id],
            ['nome' => 'Arménia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Azerbaijão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Bangladexe', 'continente_id' => $continente_asia->id],
            ['nome' => 'Barém', 'continente_id' => $continente_asia->id],
            ['nome' => 'Brunei', 'continente_id' => $continente_asia->id],
            ['nome' => 'Butão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Camboja', 'continente_id' => $continente_asia->id],
            ['nome' => 'Catar', 'continente_id' => $continente_asia->id],
            ['nome' => 'Cazaquistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'China', 'continente_id' => $continente_asia->id],
            ['nome' => 'Coreia do Norte', 'continente_id' => $continente_asia->id],
            ['nome' => 'Coreia do Sul', 'continente_id' => $continente_asia->id],
            ['nome' => 'Cuaite', 'continente_id' => $continente_asia->id],
            ['nome' => 'Emirados Árabes Unidos', 'continente_id' => $continente_asia->id],
            ['nome' => 'Estado da Palestina', 'continente_id' => $continente_asia->id],
            ['nome' => 'Filipinas', 'continente_id' => $continente_asia->id],
            ['nome' => 'Geórgia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Iémen', 'continente_id' => $continente_asia->id],
            ['nome' => 'Índia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Indonésia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Irão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Iraque', 'continente_id' => $continente_asia->id],
            ['nome' => 'Israel', 'continente_id' => $continente_asia->id],
            ['nome' => 'Japão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Jordânia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Laus', 'continente_id' => $continente_asia->id],
            ['nome' => 'Líbano', 'continente_id' => $continente_asia->id],
            ['nome' => 'Malásia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Maldivas', 'continente_id' => $continente_asia->id],
            ['nome' => 'Mianmar', 'continente_id' => $continente_asia->id],
            ['nome' => 'Mongólia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Nepal', 'continente_id' => $continente_asia->id],
            ['nome' => 'Omã', 'continente_id' => $continente_asia->id],
            ['nome' => 'Paquistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Quirguistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Singapura', 'continente_id' => $continente_asia->id],
            ['nome' => 'Síria', 'continente_id' => $continente_asia->id],
            ['nome' => 'Sri Lanca', 'continente_id' => $continente_asia->id],
            ['nome' => 'Tailândia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Taiuã', 'continente_id' => $continente_asia->id],
            ['nome' => 'Tajiquistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Turcomenistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Turquia', 'continente_id' => $continente_asia->id],
            ['nome' => 'Usbequistão', 'continente_id' => $continente_asia->id],
            ['nome' => 'Vietname', 'continente_id' => $continente_asia->id],

            ['nome' => 'Antiga e Barbuda', 'continente_id' => $continente_america->id],
            ['nome' => 'Argentina', 'continente_id' => $continente_america->id],
            ['nome' => 'Bahamas', 'continente_id' => $continente_america->id],
            ['nome' => 'Barbados', 'continente_id' => $continente_america->id],
            ['nome' => 'Belize', 'continente_id' => $continente_america->id],
            ['nome' => 'Bolívia', 'continente_id' => $continente_america->id],
            ['nome' => 'Brasil', 'continente_id' => $continente_america->id],
            ['nome' => 'Canadá', 'continente_id' => $continente_america->id],
            ['nome' => 'Chile', 'continente_id' => $continente_america->id],
            ['nome' => 'Colômbia', 'continente_id' => $continente_america->id],
            ['nome' => 'Costa Rica', 'continente_id' => $continente_america->id],
            ['nome' => 'Cuba', 'continente_id' => $continente_america->id],
            ['nome' => 'Dominica', 'continente_id' => $continente_america->id],
            ['nome' => 'Equador', 'continente_id' => $continente_america->id],
            ['nome' => 'Estados Unidos', 'continente_id' => $continente_america->id],
            ['nome' => 'Granada', 'continente_id' => $continente_america->id],
            ['nome' => 'Guatemala', 'continente_id' => $continente_america->id],
            ['nome' => 'Guiana', 'continente_id' => $continente_america->id],
            ['nome' => 'Haiti', 'continente_id' => $continente_america->id],
            ['nome' => 'Honduras', 'continente_id' => $continente_america->id],
            ['nome' => 'Jamaica', 'continente_id' => $continente_america->id],
            ['nome' => 'México', 'continente_id' => $continente_america->id],
            ['nome' => 'Nicarágua', 'continente_id' => $continente_america->id],
            ['nome' => 'Panamá', 'continente_id' => $continente_america->id],
            ['nome' => 'Paraguai', 'continente_id' => $continente_america->id],
            ['nome' => 'Peru', 'continente_id' => $continente_america->id],
            ['nome' => 'República Dominicana', 'continente_id' => $continente_america->id],
            ['nome' => 'Salvador', 'continente_id' => $continente_america->id],
            ['nome' => 'Santa Lúcia', 'continente_id' => $continente_america->id],
            ['nome' => 'São Cristóvão e Neves', 'continente_id' => $continente_america->id],
            ['nome' => 'São Vicente e Granadinas', 'continente_id' => $continente_america->id],
            ['nome' => 'Suriname', 'continente_id' => $continente_america->id],
            ['nome' => 'Trindade e Tobago', 'continente_id' => $continente_america->id],
            ['nome' => 'Uruguai', 'continente_id' => $continente_america->id],
            ['nome' => 'Venezuela', 'continente_id' => $continente_america->id],

            ['nome' => 'África do Sul', 'continente_id' => $continente_africa->id],
            ['nome' => 'Angola', 'continente_id' => $continente_africa->id],
            ['nome' => 'Argélia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Benim', 'continente_id' => $continente_africa->id],
            ['nome' => 'Botsuana', 'continente_id' => $continente_africa->id],
            ['nome' => 'Burquina Faso', 'continente_id' => $continente_africa->id],
            ['nome' => 'Burúndi', 'continente_id' => $continente_africa->id],
            ['nome' => 'Cabo Verde', 'continente_id' => $continente_africa->id],
            ['nome' => 'Camarões', 'continente_id' => $continente_africa->id],
            ['nome' => 'Chade', 'continente_id' => $continente_africa->id],
            ['nome' => 'Comores', 'continente_id' => $continente_africa->id],
            ['nome' => 'Congo-Brazzaville', 'continente_id' => $continente_africa->id],
            ['nome' => 'Costa do Marfim', 'continente_id' => $continente_africa->id],
            ['nome' => 'Egito', 'continente_id' => $continente_africa->id],
            ['nome' => 'Eritreia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Etiópia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Gabão', 'continente_id' => $continente_africa->id],
            ['nome' => 'Gâmbia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Gana', 'continente_id' => $continente_africa->id],
            ['nome' => 'Guiné', 'continente_id' => $continente_africa->id],
            ['nome' => 'Guiné Equatorial', 'continente_id' => $continente_africa->id],
            ['nome' => 'Guiné-Bissau', 'continente_id' => $continente_africa->id],
            ['nome' => 'Jibuti', 'continente_id' => $continente_africa->id],
            ['nome' => 'Lesoto', 'continente_id' => $continente_africa->id],
            ['nome' => 'Libéria', 'continente_id' => $continente_africa->id],
            ['nome' => 'Líbia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Madagáscar', 'continente_id' => $continente_africa->id],
            ['nome' => 'Maláui', 'continente_id' => $continente_africa->id],
            ['nome' => 'Mali', 'continente_id' => $continente_africa->id],
            ['nome' => 'Marrocos', 'continente_id' => $continente_africa->id],
            ['nome' => 'Maurícia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Mauritânia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Moçambique', 'continente_id' => $continente_africa->id],
            ['nome' => 'Namíbia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Níger', 'continente_id' => $continente_africa->id],
            ['nome' => 'Nigéria', 'continente_id' => $continente_africa->id],
            ['nome' => 'Quénia', 'continente_id' => $continente_africa->id],
            ['nome' => 'República Centro-Africana', 'continente_id' => $continente_africa->id],
            ['nome' => 'RRepública Democrática do Congo', 'continente_id' => $continente_africa->id],
            ['nome' => 'Ruanda', 'continente_id' => $continente_africa->id],
            ['nome' => 'São Tomé e Príncipe', 'continente_id' => $continente_africa->id],
            ['nome' => 'Seicheles', 'continente_id' => $continente_africa->id],
            ['nome' => 'Senegal', 'continente_id' => $continente_africa->id],
            ['nome' => 'Serra Leoa', 'continente_id' => $continente_africa->id],
            ['nome' => 'Somália', 'continente_id' => $continente_africa->id],
            ['nome' => 'Suazilândia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Sudão', 'continente_id' => $continente_africa->id],
            ['nome' => 'Sudão do Sul', 'continente_id' => $continente_africa->id],
            ['nome' => 'Tanzânia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Togo', 'continente_id' => $continente_africa->id],
            ['nome' => 'Tunísia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Uganda', 'continente_id' => $continente_africa->id],
            ['nome' => 'Zâmbia', 'continente_id' => $continente_africa->id],
            ['nome' => 'Zimbábue', 'continente_id' => $continente_africa->id],

            ['nome' => 'Albânia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Alemanha', 'continente_id' => $continente_europa->id],
            ['nome' => 'Andorra', 'continente_id' => $continente_europa->id],
            ['nome' => 'Áustria', 'continente_id' => $continente_europa->id],
            ['nome' => 'Bélgica', 'continente_id' => $continente_europa->id],
            ['nome' => 'Bielorrússia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Bósnia e Herzegovina', 'continente_id' => $continente_europa->id],
            ['nome' => 'Bulgária', 'continente_id' => $continente_europa->id],
            ['nome' => 'Chipre', 'continente_id' => $continente_europa->id],
            ['nome' => 'Cosovo', 'continente_id' => $continente_europa->id],
            ['nome' => 'Croácia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Dinamarca', 'continente_id' => $continente_europa->id],
            ['nome' => 'Eslováquia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Eslovénia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Espanha', 'continente_id' => $continente_europa->id],
            ['nome' => 'Estónia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Finlândia', 'continente_id' => $continente_europa->id],
            ['nome' => 'França', 'continente_id' => $continente_europa->id],
            ['nome' => 'Grécia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Hungria', 'continente_id' => $continente_europa->id],
            ['nome' => 'Irlanda', 'continente_id' => $continente_europa->id],
            ['nome' => 'Islândia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Itália', 'continente_id' => $continente_europa->id],
            ['nome' => 'Letónia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Listenstaine', 'continente_id' => $continente_europa->id],
            ['nome' => 'Lituânia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Luxemburgo', 'continente_id' => $continente_europa->id],
            ['nome' => 'Macedónia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Malta', 'continente_id' => $continente_europa->id],
            ['nome' => 'Moldávia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Mónaco', 'continente_id' => $continente_europa->id],
            ['nome' => 'Montenegro', 'continente_id' => $continente_europa->id],
            ['nome' => 'Noruega', 'continente_id' => $continente_europa->id],
            ['nome' => 'Países Baixos', 'continente_id' => $continente_europa->id],
            ['nome' => 'Polónia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Portugal', 'continente_id' => $continente_europa->id],
            ['nome' => 'Reino Unido', 'continente_id' => $continente_europa->id],
            ['nome' => 'República Checa', 'continente_id' => $continente_europa->id],
            ['nome' => 'Roménia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Rússia', 'continente_id' => $continente_europa->id],
            ['nome' => 'São Marinho', 'continente_id' => $continente_europa->id],
            ['nome' => 'Sérvia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Suécia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Suíça', 'continente_id' => $continente_europa->id],
            ['nome' => 'Ucrânia', 'continente_id' => $continente_europa->id],
            ['nome' => 'Vaticano', 'continente_id' => $continente_europa->id],

            ['nome' => 'Austrália', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Fiji', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Ilhas Marechal', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Micronésia', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Nauru', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Nova Zelândia', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Palau', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Papua Nova Guiné', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Quiribáti', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Salomão', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Samoa', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Timor-Leste', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Tonga', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Tuvalu', 'continente_id' => $continente_oceanea->id],
            ['nome' => 'Vanuatu', 'continente_id' => $continente_oceanea->id],
        ]);
    }
}
